### PR TITLE
Fix Windows builds

### PR DESCRIPTION
**Pull request by njwhite**
...as it doesn't ship with `sys/queue.h`!

### CODE REVIEW

**Comment by njwhite** [comment]
@jlaine hi - can I get a review? It's only a fix to the build system, so I'm not sure the code coverage errors matter. Thanks -

**Comment by jlaine** [comment]
Indeed we don't care about the test coverage on `setup.py`. If we're going to provide official support for Windows I would like this to be included in the continuous integration run, what's the best way to do this nowadays (appveyor / travis / github actions)?

**Comment by njwhite** [comment]
@jlaine I've seen appveyor used on Numba, but am not too sure. This is the first Windows code I've worked on in a long time!

**Comment by jlaine** [comment]
OK, in the end I merged this in 96bd6c92511406c63b9cff7fea8b18a59ac8a89a which also triggers an appveyor build. As a bonus, we will get binary wheels for Windows on the next release!

**Pull request closed without merging**
